version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: fiesc-backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=cafeteria
    depends_on:
      - db
    volumes:
      - ./backend:/app
    networks:
      - fiesc-network

  db:
    image: postgres:14
    container_name: fiesc-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cafeteria
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - fiesc-network

  frontend:
    build:
      context: ./frontend
    container_name: fiesc-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - fiesc-network

  cypress:
    image: cypress/included:13.7.3
    container_name: fiesc-cypress
    working_dir: /e2e
    volumes:
      # Monte a pasta de testes E2E, crie a pasta 'cypress' na raiz e coloque seus testes lá
      - ./cypress:/e2e
    depends_on:
      - frontend
    networks:
      - fiesc-network
    entrypoint: ["npx", "cypress", "open"]

volumes:
  pgdata:

networks:
  fiesc-network:
    driver: bridge
